### ISSUE TITLE
Determine the future of this repository

### ISSUE THREAD

**Issue by michalszynkiewicz** [smallrye/smallrye-testing#1]
@kenfinnigan this repo has been empty for quite some time.
Do you have some specific plan of what should be added here?
If not, can it be dropped?

**Comment by kenfinnigan** [comment]
Originally the idea was to share some kind of testing framework, or the like.

Not sure if that still applies, but there may be something we can do that's common across them

**Comment by michalszynkiewicz** [comment]
Okay, let's leave it then
